Server base
ChicoState/HappyHouseplants pull request #53
Opened 2020-10-07 22:44 UTC by Cessna210

2020-10-08 01:00 UTC, myothra7777 approved these changes

2020-10-12 22:38 UTC, Neodusk requested changes

2020-10-12 22:38 UTC, Neodusk commented on backend/server.js
> +});
You should be able to pull test tips from the database now, can we change this to not be a mock tip?

2020-10-12 22:38 UTC, Neodusk commented on backend/server.js
> +    userId: req.params.userId,
see above

2020-10-12 22:44 UTC, closed without merging